### PR TITLE
Feature 345 summary in reports (part 2)

### PR DESCRIPTION
**Pull request by zigfridus**
This PR switched from develop to community branch and continiue the #2156.
This PR will close the #345.

### CODE REVIEW

**Comment by zigfridus** [comment]
@Jeeppler 
I little bit confused with switching to the new community branch. At this moment I closed previous [PR](https://github.com/mercedes-benz/sechub/pull/2156) and created this PR. In my fork the [branch](https://github.com/zigfridus/sechub/tree/feature-345-summary-in-reports) still points to the develop branch. And there are a lot of conflicts:
image
I really don't want to destroy my work and I would like to ask for more detailed explanation, what should I do next to resolve those conflicts. 
Thanks

**Comment by Jeeppler** [comment]
@zigfridus you can ignore the GitHub WebUI message, the message is nonsense. Your branch `zigfridus:feature-345-summary-in-reports` has only one conflict with the community branch: `sechub-api-java/src/main/resources/reduced-openapi3.json` and that is expected.

At the moment keep things how they are. @de-jcup will inform you about the next steps. However, keep in mind that we currently have Christmas/winter holidays and a response might take time.

**Comment by Jeeppler** [comment]
@zigfridus one additional note: Do not press the button in the GitHub WebUI and do not sync with the develop branch of `mercedes-benz/sechub:develop` right now.

**Comment by zigfridus** [comment]
@Jeeppler 
Thank you for your advice. Then I'm going to work on another issue.

**Comment by zigfridus** [comment]
@Jeeppler 
As I see there is the same problem with `reduced-openapi3.json` as it was in #2781. Should I fix it as well?

**Comment by Jeeppler** [comment]
@zigfridus no, you probably have to run/test the code a couple of times and as a result you will regenerate the `reduced-openapi3.json` a couple of times. Wait for @de-jcup and what he has to say.

**Comment by zigfridus** [comment]
@Jeeppler 
Ok, thank you.

**Comment by de-jcup** [comment]
@zigfridus : Another option is to just copy `reduced-openapi3.json` from `develop` branch to your branch and the merge conflict problem is solved...

**Comment by zigfridus** [comment]
@de-jcup 
Fixed merge problem with of your second option. Thank you.

**Comment by de-jcup** [comment]
@zigfridus : Thank you for your contribution (and your patience).

**Comment by de-jcup** [comment]
Unfortunately I merged all 62 commits into the community branch instead of doing this by one commit. I will handle this on final commit to develop branch.

**Comment by de-jcup** [comment]
Created final PR at https://github.com/mercedes-benz/sechub/pull/2873.
Contains all changes from @zigfridus - final merge to develop will be squashed.

**Comment by Jeeppler** [comment]
@zigfridus thank you for your contribution.

**Comment by Jeeppler** [comment]
@zigfridus thank you again for your valuable contribution. The summary allows security experts to so much faster understand what security issues are in the report. It is a real time saver. Thank you again for your good work 👍.

**Pull request merged**
