### PR TITLE
Feature 2933 rename to pdssecretscanconfigbuilder

### PR DESCRIPTION
**Pull request by steleow**
Rename PDSSecretScanConfigImpl's PDSLicenseScanConfigBuilder's static class to PDSSecretScanConfigBuilder to standardized the naming convention.

### CODE REVIEW

**Comment by CLA-Mercedes-Benz** [comment]
[CLA assistant check](https://cla.opensource.mercedes-benz.com/mercedes-benz/sechub?pullRequest=2934) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.mercedes-benz.com/mercedes-benz/sechub?pullRequest=2934) before we can accept your contribution.<br/><hr/>**Stephen Leow** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.mercedes-benz.com/check/mercedes-benz/sechub?pullRequest=2934) it.</sub>

**Comment by sven-dmlr** [comment]
Hi @steleow thanks for the contribution! :+1: 
This pull request seems to contain more changes than you did.
The changes from me @sven-dmlr and @de-jcup are already in the `community` branch.

I suspect your "force-push" caused this.
Can you please create a new PR that contains only your changes?
(The branches `community` and `develop` are even)

Thanks in advance.

**Comment by de-jcup** [comment]
@steleow - thanx for the contribution, but looking at the commits (like @sven-dmlr explained before) there is something wrong with the history.

Maybe you did not rebase on pulls and you used merges instead?

Our git setup is described at
https://mercedes-benz.github.io/sechub/latest/sechub-techdoc.html#sechub-wanted-setup

Because the PR says `BasicAuthUserExtraction.java` is not in origin/community, but

looking at https://github.com/mercedes-benz/sechub/blob/community/sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/logging/BasicAuthUserExtraction.java

shows it is, we have an odd situation inside the PR.

So also from my side: Could you please create a new PR that contains only your changes?

_Remark: I noticed that the git setup is not documented in Developer Quickstart guide, so I created an issue for  this at https://github.com/mercedes-benz/sechub/issues/2959._

**Comment by steleow** [comment]
hi @sven-dmlr, @de-jcup Sure, I will close this PR and create a new PR for the changes.

**Pull request closed without merging**
