### PR TITLE
feat: improve scan and implement falsePositives

### PR DESCRIPTION
**Pull request by tvcsantos**
This PR adds support for false positives on GitHub actions by implementing `falsePositives` action. This action works for the following SecHub CLI actions:

- `defineFalsePositives` with input `action` specified as `DEFINE`.
- `markFalsePositives` with input `action` specified as `MARK`.
- `unmarkFalsePositives` with input `action` specified as `UNMARK`.

This PR also improves and fixes `scan` action to be fully working with the latest client version. Previous `getReport` was failing since `getReport` does not support the additional input `--reportformat`. According to documentation `getReport` on CLI always outputs in JSON. This PR fixes that.

In addition also improved CLI binaries release download by using GitHub tool cache, so that we can download and cache the tool in runners.

Closes: #2078

### CODE REVIEW

**Comment by CLA-Mercedes-Benz** [comment]
[CLA assistant check](https://cla.opensource.mercedes-benz.com/mercedes-benz/sechub?pullRequest=2911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.mercedes-benz.com/mercedes-benz/sechub?pullRequest=2911) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.mercedes-benz.com/check/mercedes-benz/sechub?pullRequest=2911) it.</sub>

**Comment by de-jcup** [comment]
@tvcsantos 
Thank you for your contribution - currently I am still doing a rewrite of the github action inside https://github.com/mercedes-benz/sechub/pull/2864.

Unfortunately I have much parallel tasks to do at the moment and it will still take some time until #2864 is finally done.

When I am done with it, I would inform you inside the PR about further steps.
Hope this is okay for you?

**Comment by tvcsantos** [comment]
@de-jcup Yup all good on my side 👍 . Feel free to ping me afterwards.

**Comment by sven-dmlr** [comment]
Hi @tvcsantos 
now the remake of our SecHub scan GH action finally has been finished.
Sorry for the long time it took. :-)

We would like to close this PR.

We would greatly appreciate to receive your contributions
- regarding caching of the downloaded client (see #3199) -> please create a separate PR for this topic
- regarding defineFalsePositives functionality (see #3244) -> please create a separate PR for this topic

When #3244 is implemented then IMHO a separate action ( #2078 ) is no longer necessary.

Best regards

Sven

**Comment by tvcsantos** [comment]
Hey @sven-dmlr thanks for the reply.

Okay I will take a peek at the new action and check if I can include those features.

I will close this PR ;)

**Comment by tvcsantos** [comment]
FYI. Cache topic addressed on #3320 ;)

**Pull request closed without merging**
