### PR TITLE
feat: implement gha caching for client download 

### PR DESCRIPTION
**Pull request by tvcsantos**
Add support for caching client download.

Also did a cleanup on linter issues and some missing comments.

Closes https://github.com/mercedes-benz/sechub/issues/3199

### CODE REVIEW

**Comment by hamidonos** [comment]
@tvcsantos the workflow is running now :)

**Comment by haerter-tss** [comment]
Hello @tvcsantos !
I noticed that there are some merge conflicts in the pull request you opened. When you have a moment, could you please take a look and resolve these conflicts?

Thank you for your contribution!

**Comment by sven-dmlr** [comment]
Meanwhile we have added caching of the SecHub client ourselves.
(Action will be released soon)

Anyway: Thanks for your contribution.

**Comment by tvcsantos** [comment]
> Meanwhile we have added caching of the SecHub client ourselves. (Action will be released soon)
> 
> Anyway: Thanks for your contribution.

okay thanks :+1:

**Pull request closed without merging**
