### PR TITLE
Feature 651 tmp files inside build folders

### LINKED ISSUE #651: Cleanup /tmp leftovers from builds and integration tests
When building and running integration tests, temporary files and directories are created in /tmp.

Unfortunately not all are removed afterwards so after a while hundreds of files and directories accumulate in /tmp.
Although a reboot cleans /tmp, we should leave /tmp clean after our builds and integration tests.

File patterns to clean up:
- pds_executable*.sh
- log_fullscan*.zip
- storage_test*.txt
- mark_as_false_positive*.json
- unmark_false_positive*.json

Directory patterns to clean up:
- sechub-temp-sharedvolume*
- s3mockFileStore*
- tomcat.*
- with-sechub-client-*
- sechub-assertzip*
- sechub-scenario_testdata*.properties
- subFolder

---
Real life example from one run:
```
---x------ 1 jenkins jenkins       0 Jun  1 10:02 pds_executable8236953800377398000.sh*
-rw------- 1 jenkins jenkins       0 Jun  1 10:02 pds_executable6992790267118136904.sh
drwx------ 2 jenkins jenkins       6 Jun  1 10:02 sechub-temp-sharedvolume6839503372988020827/
-rw-r--r-- 1 jenkins jenkins     932 Jun  1 10:03 log_fullscan8466918723963510764.zip
-rw-r--r-- 1 jenkins jenkins    1581 Jun  1 10:03 log_fullscan5595143633442393252.zip
drwx------ 2 jenkins jenkins       6 Jun  1 10:03 sechub-temp-sharedvolume8552399949479873340/
drwx------ 2 jenkins jenkins       6 Jun  1 10:03 sechub-temp-sharedvolume6068586466766046810/
drwx------ 2 jenkins jenkins       6 Jun  1 10:03 sechub-temp-sharedvolume1511647070267518962/
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test5586591023371467151.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test6475742242348785540.txt
-rw------- 1 jenkins jenkins      11 Jun  1 10:03 storage_test9044449355667303720.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test4300826880524830090.txt
drwxr-xr-x 4 jenkins jenkins      37 Jun  1 10:03 s3mockFileStore1622534627613/
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test8143636811107637282.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test1096131970181585114.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test7967394974045286704.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test4555800278417378051.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test2913165529244878622.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test9058230212804587301.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test806717370169290316.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test7193105979460895472.txt
-rw------- 1 jenkins jenkins       0 Jun  1 10:03 storage_test8387023165431267889.txt
-rw------- 1 jenkins jenkins       9 Jun  1 10:03 storage_test582981353114354628.txt
drwx------ 3 jenkins jenkins      18 Jun  1 10:04 tomcat.8544.10243067071344118690/
drwx------ 3 jenkins jenkins      18 Jun  1 10:04 tomcat.8244.13976441950780643502/
drwx------ 3 jenkins jenkins      18 Jun  1 10:04 tomcat.10250.11967401138870333631/
drwx------ 2 jenkins jenkins      86 Jun  1 10:05 with-sechub-client-4678407109354887354/
drwx------ 2 jenkins jenkins      86 Jun  1 10:05 with-sechub-client-3118827199485677474/
drwx------ 2 jenkins jenkins      86 Jun  1 10:05 with-sechub-client-2265871281572771655/
drwx------ 2 jenkins jenkins      86 Jun  1 10:05 with-sechub-client-4467117656148799228/
drwx------ 2 jenkins jenkins      86 Jun  1 10:05 with-sechub-client-3686161842431694567/
drwx------ 2 jenkins jenkins      86 Jun  1 10:05 with-sechub-client-759240214864207380/
drwx------ 2 jenkins jenkins      86 Jun  1 10:05 with-sechub-client-7051618102537393125/
drwx------ 2 jenkins jenkins      86 Jun  1 10:05 with-sechub-client-7870163070466237451/
drwx------ 2 jenkins jenkins      86 Jun  1 10:05 with-sechub-client-604357516171574855/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-9220699079594911194/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-4247903888374473610/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-2009202800528672735/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-5915564641646102558/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-5689443186537794637/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-6429595575413558380/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-3886011479329154055/
drwx------ 3 jenkins jenkins      47 Jun  1 10:06 sechub-assertzip6746876328513593936/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-3171080367070804851/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-3518018763169218047/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-5578003751626892206/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-1696720958893193694/
drwx------ 2 jenkins jenkins      86 Jun  1 10:06 with-sechub-client-3827367260861293943/
drwx------ 2 jenkins jenkins      86 Jun  1 10:07 with-sechub-client-8464553539501266954/
drwx------ 2 jenkins jenkins      86 Jun  1 10:07 with-sechub-client-3185211480735609725/
drwx------ 2 jenkins jenkins      86 Jun  1 10:07 with-sechub-client-7307154826576732371/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-655072611241517609/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-4749270603308130342/
-rw-r--r-- 1 jenkins jenkins     131 Jun  1 10:08 mark_as_false_positive873409733278306278.json
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-3419228027649590160/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-4191546693157847363/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-8938033259662341309/
-rw-r--r-- 1 jenkins jenkins     131 Jun  1 10:08 unmark_false_positive6767659908000357166.json
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-8883730356983580366/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-5075492606925467549/
drwx------ 2 jenkins jenkins      58 Jun  1 10:08 with-sechub-client-2764369372157030371/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-449190917199961896/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-5905499619465102546/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-4004772229890686512/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-2821306739209072489/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-6213132985494604991/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-96914293270544212/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-4673393211713181840/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-3349940348190912906/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-4553633162592415738/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-1345506297552407271/
drwx------ 2 jenkins jenkins      86 Jun  1 10:08 with-sechub-client-3873413061472663037/
drwx------ 2 jenkins jenkins      86 Jun  1 10:09 with-sechub-client-3652545646256616243/
drwx------ 2 jenkins jenkins      86 Jun  1 10:09 with-sechub-client-1179872948869510886/
drwx------ 2 jenkins jenkins      86 Jun  1 10:09 with-sechub-client-6292466920944165546/
-rw------- 1 jenkins jenkins       0 Jun  1 10:09 sechub-scenario_testdata6927795937188142388.properties
-rw------- 1 jenkins jenkins      97 Jun  1 10:09 sechub-scenario_testdata3760698308811491769.properties
-rw------- 1 jenkins jenkins      97 Jun  1 10:09 sechub-scenario_testdata548958584516403127.properties
-rw------- 1 jenkins jenkins      98 Jun  1 10:09 sechub-scenario_testdata7947042295366208134.properties
drwxr-xr-x 2 jenkins jenkins       6 Jun  1 10:10 subFolder/
```

### PR DESCRIPTION
**Pull request by de-jcup**
This PR
- closes #651

### CODE REVIEW

**Review by sven-dmlr — CHANGES_REQUESTED** [review]
Great improvements compared to before! :+1: 

## Tests
Ran these builds/commands:
```
./buildDoc
./buildExecutables
./gradlew ensureLocalhostCertificate build generateOpenapi buildDeveloperAdminUI -x :sechub-integrationtest:test -x :sechub-cli:build
./gradlew clean
```
and then checked for leftovers

## Results
### processes still running afterwards:
`java -jar ./../sechub-pds/build/libs/sechub-pds-0.0.0.jar`
-> This process should be stopped.

### leftover files in /tmp (sizes in comments behind):
```
> gradle-worker-classpath10235308889282357354txt
> gradle-worker-classpath11077408683844615828txt
> gradle-worker-classpath11867196760834489104txt
> gradle-worker-classpath11897705710349025992txt
> gradle-worker-classpath13299128963528726941txt
> gradle-worker-classpath13584283391624994218txt
> gradle-worker-classpath1393458648160657072txt
> gradle-worker-classpath13975243552784172200txt
> gradle-worker-classpath14512927099358265354txt
> gradle-worker-classpath15185670419373424854txt
> gradle-worker-classpath15698324164426567855txt
> gradle-worker-classpath15757762613356817679txt
> gradle-worker-classpath16136459290713264302txt
> gradle-worker-classpath16326979570695220099txt
> gradle-worker-classpath16438330847932066216txt
> gradle-worker-classpath16635164805345879737txt
> gradle-worker-classpath16653954074937518357txt
> gradle-worker-classpath16866114486618688466txt
> gradle-worker-classpath18092776259640447583txt
> gradle-worker-classpath18368244573559091808txt
> gradle-worker-classpath224712190139656797txt
> gradle-worker-classpath2518132646102314665txt
> gradle-worker-classpath3200536774784305505txt
> gradle-worker-classpath3495218684563503385txt
> gradle-worker-classpath3820244983745002505txt
> gradle-worker-classpath3991098814718612107txt
> gradle-worker-classpath4417741120377909598txt
> gradle-worker-classpath4529331796229769554txt
> gradle-worker-classpath4931136396112746978txt
> gradle-worker-classpath4979070801830623767txt
> gradle-worker-classpath5454677819772244910txt
> gradle-worker-classpath5606665254360764249txt
> gradle-worker-classpath7907465979488353145txt
> gradle-worker-classpath8415666943081519502txt
> gradle-worker-classpath8551639695552948633txt

> sechub-inttest15511987697992823166/            # 5.3m

> sechub-temp-sharedvolume11387562942178462821/  # 4k
> sechub-temp-sharedvolume12121261992107954452/  # 4k
> sechub-temp-sharedvolume2165678366783832922/   # 4k
> sechub-temp-sharedvolume9490342016952968546/   # 4k

> subFolder/                                     # empty

> tomcat.10250.2304677693773478654/              # 20k
> tomcat.8443.11066230722227992363/              # 20k
> tomcat.8444.16277951231724602540/              # 20k
> tomcat-docbase.8444.12620704415928972613/      # 4k (will be removed automatically when PDS process is stopped)
```
-> Please check if these files can also be removed as cleanup.

**Comment by de-jcup** [comment]
sechub-temp-sharedvolume11387562942178462821/ etc. is created, because in normal tests (not integration tests) when a test spring container has been started, this is a fallback when no setup has been done for the shared volume.

This is something that should not happen with S3 setup.
I will change the naming to `sechub-fallback-sharedvolume" so it's more clear its only a fallback, when shared volume is not set.

For people wanting no such temp files inside their Jenkins builds, they just need to setup the shared volume settings as env variables for their jobs.

So I will not do more here (except the renaming and some log improvments)

**Comment by de-jcup** [comment]
sechub-inttest15511987697992823166/

is the temp folder defined by gradle for integration tests.
I will change the gradle script accordingly so we have those outputs in build folders as well

**Comment by de-jcup** [comment]
gradle-worker-*****

comes from gradle - cannot change this.

**Comment by de-jcup** [comment]
subFolder

This comes from a textwriter test - will change it .

**Comment by de-jcup** [comment]
PDS server not stopping...
I tried out and really, the PDS is not stopping when e.g. `buildDoc`has been run.

Even a manual `./graldew stopIntegrationTestPDS` does not work
Will create an extra issue for this.

**Comment by de-jcup** [comment]
I created #998 to handle the PDS integration test shutdown problems - as it is major problem with the PDS itself, it will not be handled this PR.

**Pull request merged**
