### PR TITLE
feat: implement gha caching for client download

### LINKED ISSUE #3199: Implement caching for GitHub Actions client download
## Situation
Currently the client (20mb) is downloaded every time the build pipeline runs because no caching is implemented.

## Wanted
- The client is cached by its version.
   For example: 1.6.1 is only downloaded once for every run

- Also the download should be logged properly so that the client knows that something is happening.
   Log the client version that is downloaded and progress etc.

### PR DESCRIPTION
**Pull request by tvcsantos**
Add support for caching client download.

Also did a cleanup on linter issues and some missing comments.

Closes #3199

### CODE REVIEW

**Comment by hamidonos** [comment]
Hi @tvcsantos 

unfortunately I cannot run the GitHub action workflow for PRs from a fork (this must be a limitation from our organization)
While we try to resolve this I would kindly ask you to try to open the pull request directly on our `community` branch.

From there the GH action workflow should be able to run

**Comment by tvcsantos** [comment]
> Hi @tvcsantos
> 
> unfortunately I cannot run the GitHub action workflow for PRs from a fork (this must be a limitation from our organization) While we try to resolve this I would kindly ask you to try to open the pull request directly on our `community` branch.
> 
> From there the GH action workflow should be able to run

Changed the base branch to the community one.

**Comment by hamidonos** [comment]
Hi @tvcsantos 

Unfortunately the workflow still does not run for your PR. I think the problem is due to an event missing in the workflow configuration. See #3357 for more information.

We'll refine this issue soon and try to fix it as soon as possible. I'll keep you posted.

Sorry for any inconveniences.

**Comment by hamidonos** [comment]
Hello @tvcsantos 

#3357 has been implemented. But checks did not run for you PR yet.

I assume we have to either trigger an action by a dummy commit or pull request recreation.

**Comment by sven-dmlr** [comment]
I'll give it a try closing and re-opening it....

**Comment by sven-dmlr** [comment]
It did not help :see_no_evil:

**Comment by tvcsantos** [comment]
Did a dummy commit. I think there was no trigger

**Comment by hamidonos** [comment]
Can you please merge the current `develop` branch into your PR?

**Comment by tvcsantos** [comment]
> Can you please merge the current `develop` branch into your PR?

Should i target develop on the PR?

**Comment by hamidonos** [comment]
We've changed the settings on this repository 
I think its best if you close this PR and reopen it 
merge into `develop` 
you should name your branch something like `gha_feature-3323-implement-caching-gha` (note that we put the issue number before the branch description)

sorry for the back and forth

**Comment by tvcsantos** [comment]
okay will do that 🤞

**Comment by tvcsantos** [comment]
#3441

**Pull request closed without merging**
