### PR TITLE
Feature 2328 create pds solution for phan

### PR DESCRIPTION
**Pull request by zigfridus**
Pull request for #2328

### CODE REVIEW

**Comment by zigfridus** [comment]
@Jeeppler 
I configured PMD to work with PHAN in the single container. 
For testing purpose I used the PHP code from here [https://phan.github.io/demo/](https://phan.github.io/demo/)
Please have a look.

**Comment by Jeeppler** [comment]
@zigfridus it seems you branched of the other changes of yours. Currently, it shows you have 80 commits and 136 files are changes. As a result there are many merge conflicts.

**Comment by zigfridus** [comment]
@Jeeppler 
Sorry for that. I'll fix it.

**Comment by Jeeppler** [comment]
@zigfridus don't worry. Part of the learning process.

**Pull request closed without merging**
